name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'gradle'

      # -------------------
      # Build & Test Client
      # -------------------

      - name: Grant execute permission to Gradlew (Client)
        run: chmod +x ./client/gradlew

      - name: Build Client with Gradle
        working-directory: ./client
        run: ./gradlew shadowJar

      - name: Run Client Tests
        working-directory: ./client
        run: ./gradlew test

      - name: Upload Client Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-shadow-jar
          path: client/app/build/libs/*.jar

      # -------------------
      # Build & Test Server
      # -------------------

      - name: Grant execute permission to Gradlew (Server)
        run: chmod +x ./server/gradlew

      - name: Build Server with Gradle
        working-directory: ./server
        run: ./gradlew shadowJar

      - name: Run Server Tests
        working-directory: ./server
        run: ./gradlew test

      - name: Upload Server Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-shadow-jar
          path: server/app/build/libs/*.jar